hmcts/ia-hearings-api

config/checkstyle/checkstyle.xml, config/owasp/suppressions.xml
RIA-7385
Removed exceedingly pedantic checkstyle rules and added a suppression
```
[ ] Yes
[x] No
```
=> RIA-7385 Removed exceedingly pedantic checkstyle rules

build.gradle, config/owasp/suppressions.xml
RIA-7725
Solve some suppressions
```
[ ] Yes
[x] No
```
=> RIA-7725 Solve suppressions

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/InterpreterDetails.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/InterpreterDetailsMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/PartyDetailsMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/HearingService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/InterpreterDetailsMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/PartyDetailsMapperTest.java
=> RIA-7702 - Interpreters are included as a party in the hearing request

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/StrategicCaseFlag.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/WitnessDetails.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/AppellantDetailsMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseFlagsToServiceHearingValuesMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LegalRepDetailsMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LegalRepOrgDetailsMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/RespondentDetailsMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/SponsorDetailsMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/WitnessDetailsMapper.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/StrategicCaseFlagTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/AppellantDetailsMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseFlagsToServiceHearingValuesMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LanguageAndAdjustmentsMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LegalRepDetailsMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LegalRepOrgDetailsMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/RespondentDetailsMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/SponsorDetailsMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/WitnessDetailsMapperTest.java
https://tools.hmcts.net/jira/browse/RIA-7753
```
[ ] Yes
[x] No
```
=> RIA-7753 Party ID field mapping in manual request

charts/ia-hearings-api/Chart.yaml, charts/ia-hearings-api/values.yaml, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/hmc/IndividualDetailsModel.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/hmc/PartyDetailsModel.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/hmc/ServiceHearingValuesModel.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LegalRepOrgDetailsMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/RespondentDetailsMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/HearingService.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProvider.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/controllers/HearingsController.java, src/main/resources/application.yaml, src/main/resources/screenFlowMinusPanel.json, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LegalRepOrgDetailsMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/RespondentDetailsMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/HearingServiceTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProviderTest.java, src/test/resources/screenFlowTest.json
[RIA-7860](https://tools.hmcts.net/jira/browse/RIA-7860)
- Added all necessary changes to make the hearings tab work locally
- Some data is hardcoded and is going to be updated by future tickets that'll pass the appropriate dynamic values
```
[ ] Yes
[x] No
```
=> RIA-7860 hearings tab setup

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/CaseFlagDetail.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/PartyFlagIdValue.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/StrategicCaseFlag.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseFlagsToServiceHearingValuesMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LanguageAndAdjustmentsMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProvider.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/PartyFlagIdValueTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseFlagsToServiceHearingValuesMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LanguageAndAdjustmentsMapperTest.java
https://tools.hmcts.net/jira/browse/RIA-7869
```
[ ] Yes
[x] No
```
=> RIA-7869 Allow unique identifying of flags based off witnesses

charts/ia-hearings-api/Chart.yaml, charts/ia-hearings-api/values.yaml
RIA-7910 Updates to fix HMC topic subscription name
RIA-7910 Updates to fix HMC topic subscription name
```
[ ] Yes
[X ] No
```
=> RIA-7910 Updates to fix HMC topic subscription name

src/main/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/controllers/HearingsController.java
https://tools.hmcts.net/jira/browse/RIA-7914
updates to expose service hearing values under root
```
[ ] Yes
[X ] No
```
=> RIA-7914 updates to expose service hearing values under root

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LegalRepOrgDetailsMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/RespondentDetailsMapper.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LegalRepOrgDetailsMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/RespondentDetailsMapperTest.java
https://tools.hmcts.net/jira/browse/RIA-7665
Fix hearings submit process adding organisational information and deleting individual information.
```
[ ] Yes
[X] No
```
=> RIA-7665 Fix hearings submit process adding organisational information and deleting individual information.

.github/workflows/pr-title-validation.yml, Jenkinsfile_nightly, audit.json, build.gradle, config/owasp/suppressions.xml, gradle/wrapper/gradle-wrapper.properties, src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/WelcomeTest.java
https://tools.hmcts.net/jira/browse/DIAC-51
```
[ ] Yes
[x] No
```
=> DIAC-51 nightly fixes

.github/renovate.json
renovate shouldn't be set to auto merge yet so turning off
```
[ ] Yes
[ ] No
```
=> DIAC-51  renovate automerge off after previous merge

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProvider.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProviderTest.java
RIA-7923 Updates to fix loading screen flow from classpath
RIA-7923 Updates to fix loading screen flow from classpath
```
[ ] Yes
[X ] No
```
=> RIA-7923 Updates to fix loading screen flow from classpath

audit.json, build.gradle
=> DIAC-000 Dependency fix

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/hmc/HearingWindowModel.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/hmc/ServiceHearingValuesModel.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProvider.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProviderTest.java
https://tools.hmcts.net/jira/browse/RIA-7823
RIA-7823 Fix sla and fixDate bug
=> RIA-7823 Fix sla and fixDate bug

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CoreCaseDataService.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/HearingService.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/config/SecurityConfiguration.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CoreCaseDataServiceTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/HearingServiceTest.java
Reverts hmcts/ia-hearings-api#205
=> Revert "RIA-7943 - Change to use the user token being passed in instead of system user t…"

charts/ia-hearings-api/Chart.yaml, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LanguageAndAdjustmentsMapper.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LanguageAndAdjustmentsMapperTest.java
https://tools.hmcts.net/jira/browse/RIA-7617
```
[ ] Yes
[x] No
```
=> RIA-7617 Include sign language in party's reasonable adjustment list

src/main/resources/application.yaml
=> RIA-7617 Fix typo in caseofficer role

charts/ia-hearings-api/Chart.yaml, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/hmc/ListAssistCaseStatus.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditListCaseHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/HandlerUtils.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/HearingExceptionHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListCaseHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/UpdateHmcResponseEventHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CoreCaseDataService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditListCaseHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/HearingExceptionHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListCaseHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/UpdateHmcResponseEventHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CoreCaseDataServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-7882
RIA-7882 Trigger edit case listing event
```
[ ] Yes
[X ] No
```
=> RIA-7882 Trigger edit case listing event

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/RecordAdjournmentUpdateRequestHandler.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/RecordAdjournmentUpdateRequestHandlerTest.java
https://tools.hmcts.net/jira/browse/RIA-7830
=> RIA-7830 - trigger call to update hearing

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/AppellantDetailsMapper.java
(https://tools.hmcts.net/jira/browse/RIA-8009)
```
[ ] Yes
[x ] No
```
=> RIA-8009 - Remove Title in Appellant Party for request message

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/WitnessDetails.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/WitnessDetailsMapperTest.java
[RIA-7922](https://tools.hmcts.net/jira/browse/RIA-7922)
- Updated WitnessDetails class
=> RIA-7792 Add field to WitnessDetails

src/main/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/hmc/listeners/HmcHearingsEventTopicListener.java
[RIA-8020](https://tools.hmcts.net/jira/browse/RIA-8020)
- Log message when received
```
[ ] Yes
[x] No
```
=> RIA-8020 Log message when received

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java
=> RIA-7668 - update field

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/hmc/ListAssistCaseStatus.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditCaseListingAfterAdjournmentHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditListCaseHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListCaseHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/SubstantiveListedHearingService.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CoreCaseDataService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditCaseListingAfterAdjournmentHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditListCaseHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CoreCaseDataServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-7900
```
[ ] Yes
[x] No
```
=> RIA-7900 Trigger 'editCaseListing' event when substantive hearing is listed after adjournment

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapper.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapperTest.java
https://tools.hmcts.net/jira/browse/RIA-8002
- Set the value of earliest start date to current date + 10 working days
- Set the empty value of latest end date
- Updated the unit test for earliest start date and latest end date
```
[ ] Yes
[X] No
```
=> RIA-8002 set hearing window for manual request message

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/hmc/AppealType.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/hmc/CaseTypeValue.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProvider.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProviderTest.java
https://tools.hmcts.net/jira/browse/RIA-7446
```
[ ] Yes
[ x] No
```
=> RIA-7446 -  Set case category type and value for hearing request and update

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProvider.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProviderTest.java
=> RIA-7446 - Corrected case type values

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/Facilities.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/RecordAdjournmentUpdateRequestHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingRequestSubmit.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProvider.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/RecordAdjournmentUpdateRequestHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingsRequestSubmitTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProviderTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-7918
RIA-7918 set typeC facility for S94B hearing request and updates
```
[ ] Yes
[X ] No
```
=> RIA-7918 set typeC facility for S94B hearing request and updates

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/ReasonCodes.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/RecordAdjournmentUpdateRequestHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateInterpreterDetailsHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingsRequestSubmitTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateInterpreterDetaiilsHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateInterpreterDetailsHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-7963
RIA-7963 Update HMC when interpreter details event is triggered
```
[ ] Yes
[X ] No
```
=> RIA-7963 Update HMC when interpreter details event is triggered

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingRequestHandler.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingsRequestHandlerTest.java
https://tools.hmcts.net/jira/browse/RIA-7823
RIA-7823 Fix date range issue pre populate hearingDateWindows data.
```
[ ] Yes
[X] No
```
=> RIA-7823 Fix date range issue for update hearing request

src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/CcdCaseCreationTest.java, src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/EndAppealRequestSubmitHandlerFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/HearingsControllerFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/RecordAdjournmentDetailsPreparerFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/RecordAdjournmentUpdateRequestHandlerFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/UpdateHearingRequestFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/util/IdamAuthProvider.java, src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/util/MapValueExpander.java, src/functionalTest/resources/application-functional.yaml, src/functionalTest/resources/templates/start-appeal-aip.json, src/functionalTest/resources/templates/start-appeal-legalrep.json
https://tools.hmcts.net/jira/browse/RIA-7977
```
[ ] Yes
[ x] No
```
=> RIA-7977 - Create functional tests for ia-case-api.delegator to ia-hearings-api

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingRequestSubmit.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingsRequestSubmitTest.java
=> RIA-7823 - fix for mandatory field listCaseHearingLength being removed

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/HearingsDynamicListPreparer.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/HearingsDynamicListPreparerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/RecordAdjournmentDetailsPreparerTest.java
https://tools.hmcts.net/jira/browse/RIA-7768
RIA-7768 Update hearing list with new requirements
=> RIA-7768 Update hearing list with new requirements

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/HearingsDynamicListPreparer.java
](https://tools.hmcts.net/jira/browse/RIA-7994)
```
[ ] Yes
[x ] No
```
=> RIA-7994 - Add logs to debug issue on demo

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/HearingsDynamicListPreparer.java
=> RIA-7994 -  add logs

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/HearingsDynamicListPreparer.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/HearingsDynamicListPreparerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/RecordAdjournmentDetailsPreparerTest.java
Changed hearing update status 
https://tools.hmcts.net/jira/browse/RIA-7994
```
[ ] Yes
[x ] No
```
=> RIA-7994 - add logs

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingRequestSubmit.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingsRequestSubmitTest.java
https://tools.hmcts.net/jira/browse/RIA-7768
RIA-7768 change HEARING_CENTER to LIST_CASE_HEARING_CENTRE when adjournment a hearing
```
[ ] Yes
[X] No
```
=> RIA-7768 change HEARING_CENTER to LIST_CASE_HEARING_CENTRE when adjournment a hearing

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/RecordAdjournmentUpdateRequestHandler.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/RecordAdjournmentUpdateRequestHandlerTest.java
https://tools.hmcts.net/jira/browse/RIA-7836
RIA-7836 FixRecordAdjournment submission
=> RIA-7836 FixRecordAdjournment submission.

charts/ia-cron-unnotified-hearings-processor/.helmignore, charts/ia-cron-unnotified-hearings-processor/Chart.yaml, charts/ia-cron-unnotified-hearings-processor/values.aat.template.yaml, charts/ia-cron-unnotified-hearings-processor/values.preview.template.yaml, charts/ia-cron-unnotified-hearings-processor/values.yaml
[RIA-8082](https://tools.hmcts.net/jira/browse/RIA-8082)
- Added directory with chart and value for ia-cron-unnotified-hearings-processor job
```
[ ] Yes
[x] No
```
=> RIA-8082 Add chart and values for cron job

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/hmc/CaseTypeValue.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProvider.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProviderTest.java
https://tools.hmcts.net/jira/browse/RIA-8039
```
[ ] Yes
[x] No
```
=> RIA-8039 - Set case type for float hearings

.github/renovate.json, build.gradle
https://tools.hmcts.net/jira/browse/DIAC-2
Fixing build
```
[ ] Yes
[x] No
```
=> DIAC-002 Reverting versions and turning renovate automerge off

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseFlagsToServiceHearingValuesMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseFlagsToServiceHearingValuesMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-7776
```
[ ] Yes
[x] No
```
=> RIA-7776 Decision without hearing cases are manually listed

build.gradle, config/owasp/suppressions.xml
[RIA-8155](https://tools.hmcts.net/jira/browse/RIA-8155)
- CVE-2023-6378 fix
```
[ ] Yes
[x] No
```
=> RIA-8155 CVE fix

src/main/resources/application.yaml
To increase read and connection timeout of feign client
To increase read and connection timeout of feign client
```
[ X] Yes
[ ] No
```
=> To increase read and connection timeout of feign client

src/main/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/hmc/UnNotifiedHearingsProcessor.java
Refactor batch job to allow processing to continue even if there is an exception in one of the hearings.
Refactor batch job to allow processing to continue even if there is an exception in one of the hearings.
```
[ ] Yes
[ ] No
```
=> RIA-8216 Update to allow batch processing to run uninterrupted

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/hmc/CustodyStatus.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/bail/ApplicantDetailsMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProvider.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/AppellantDetailsMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProviderTest.java
https://tools.hmcts.net/jira/browse/RIA-8042
update values
```
[ ] Yes
[ x ] No
```
=> RIA-8042 update values

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/hmc/HearingWindowModel.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/HearingWindowModelTest.java
RIA-8216 Updates to fix hearing window model serialization issue
RIA-8216 Updates to fix hearing window model serialization issue
```
[ ] Yes
[ ] No
```
=> RIA-8216 Updates to fix hearing window model serialization issue

src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/RecordAdjournmentUpdateRequestHandlerFunctionalTest.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/RecordAdjournmentUpdateRequestHandler.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/RecordAdjournmentUpdateRequestHandlerTest.java
https://tools.hmcts.net/jira/browse/RIA-7836
RIA-7836 Rename hearings cancellation/update reasons
=> RIA-7836 Rename hearings cancellation/update reasons

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/BailCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/BailListCaseHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditCaseListingAfterAdjournmentHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditListCaseHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/HearingExceptionHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListCaseHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListCmrHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/SubstantiveListedHearingService.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CoreCaseDataService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/BailListCaseHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditCaseListingAfterAdjournmentHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditListCaseHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/HearingExceptionHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListCaseHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListCmrHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CoreCaseDataServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-7969
Send standard direction to HO to provide Bail Summary
```
[ ] Yes
[ x ] No
```
=> RIA-7969 Send standard direction to HO to provide Bail Summary

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/bail/BailCaseFlagsToServiceHearingValuesMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProvider.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/bail/BailCaseFlagsToServiceHearingValuesMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProviderTest.java
https://tools.hmcts.net/jira/browse/RIA-8041
```
[ ] Yes
[x] No
```
=> RIA-8041 Populate Bails manual request message using case flags

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/BailUploadSummaryDirectionHandler.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/BailUploadSummaryDirectionHandlerTest.java
https://tools.hmcts.net/jira/browse/RIA-8112
Updated sendBailDirection to sendUploadBailSummaryDirection
```
[ ] Yes
[ x ] No
```
=> RIA-8112 updated sendBailDirection to sendUploadBailSummaryDirection

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/FeatureToggler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/HearingService.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/clients/LaunchDarklyFeatureToggler.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/HearingServiceTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/clients/LaunchDarklyFeatureTogglerTest.java
https://tools.hmcts.net/jira/browse/RIA-8346
```
[ ] Yes
[x] No
```
=> RIA-8346 Feature toggle for auto request

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/bail/BailCaseDataToServiceHearingValuesMapper.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/bail/BailCaseDataToServiceHearingValuesMapperTest.java
[https://tools.hmcts.net/jira/browse/RIA-8372](https://tools.hmcts.net/jira/browse/RIA-8372)
- populate different field of HearingWindow when specific date is supposed to be selected
```
[ ] Yes
[x] No
```
=> RIA-8372 Populate different value for specific date in HearingWindow

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/bail/BailCaseDataToServiceHearingValuesMapper.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/bail/BailCaseDataToServiceHearingValuesMapperTest.java
https://tools.hmcts.net/jira/browse/RIA-8379
The current date calculation for hearing window needs to be adjusted. 
When 2 working days are added, the resulting day should be the 3rd working day from the current day rather than the 2nd working day.
Ex : 22-Dec-2003 + 2 working days = 28-Dec-2023 Instead it should be 29-Dec-2023.
```
[ ] Yes
[X ] No
```
=> RIA-8379 Updates to fix hearing window date calculation issue

charts/ia-hearings-api/Chart.yaml, charts/ia-hearings-api/values.yaml, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/BailCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/PartyDetailsMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/bail/BailInterpreterDetailsMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProvider.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/PartyDetailsMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/bail/BailInterpreterDetailsMapperTest.java
https://tools.hmcts.net/jira/browse/RIA-8040
https://tools.hmcts.net/jira/browse/RIA-8380
Changes to populate interpreter details for bail payload generation
Remove panel requirements for  bail payload generation
Remove additional slash on deep link
```
[ ] Yes
[ ] No
```
=> RIA-8040 RIA-8380 Updates to populate interpreter party details for bails

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseFlagsToServiceHearingValuesMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/bail/BailCaseFlagsToServiceHearingValuesMapper.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseFlagsToServiceHearingValuesMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/bail/BailCaseFlagsToServiceHearingValuesMapperTest.java
https://tools.hmcts.net/jira/browse/RIA-8406
https://tools.hmcts.net/jira/browse/RIA-8390
Updates to fix case level flags being shown as undefined
```
[ ] Yes
[X ] No
```
=> RIA-8390 RIA-8046 Updates to fix case level flags being shown as undefined

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AdjournmentDetail.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditCaseListingAfterAdjournmentHandler.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditCaseListingAfterAdjournmentHandlerTest.java
https://tools.hmcts.net/jira/browse/RIA-8401
```
[ ] Yes
[x] No
```
=> RIA-8401 Address issue with 'Edit case listing' event

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/RecordAdjournmentUpdateRequestHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingRequestSubmit.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CreateHearingPayloadService.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProvider.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/RecordAdjournmentUpdateRequestHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingsRequestSubmitTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateInterpreterDetailsHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CreateHearingPayloadServiceTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProviderTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-8418
RIA-8418 Update hmc-hearing when record an Adjourn details relisting immediately
```
[ ] Yes
[X] No
```
=> RIA-8418 Update hmc-hearing when record an Adjourn details relisting immediately

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/hmc/ListingStatus.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/SubstantiveListedHearingService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/CancelledHearingHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/SubstantiveListedHearingServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-7636
Fixed incorrect statuses for Cancelled hearings.
```
[ ] Yes
[x ] No
```
=> RIA-7636 - Fixed incorrect statuses for Cancelled hearings

src/main/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/hmc/UnNotifiedHearingsProcessor.java
=> RIA-7636 - Added logs for debugging

src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/ListCaseWithoutHearingRequirementsFunctionalTest.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/AutoCreateHearingRequestHandler.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/AutoCreateHearingRequestHandlerTest.java
https://tools.hmcts.net/jira/browse/RIA-7987
```
[ ] Yes
[x] No
```
=> RIA-7987 Auto create HMC hearing request when 'Review hearing requirements' event is completed

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/BailCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/bail/ListingEvent.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/ccd/State.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/BailListCaseHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListedHearingService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/bail/ListingEventTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/ccd/StateTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/BailListCaseHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListedHearingServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-8356
Added handler for initial bail case listing
```
[ ] Yes
[ x ] No
```
=> RIA-8356 added handler for initial bail case listing

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseFlagsToServiceHearingValuesMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CreateHearingPayloadService.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProvider.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseFlagsToServiceHearingValuesMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CreateHearingPayloadServiceTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProviderTest.java
https://tools.hmcts.net/jira/browse/RIA-8363
```
[ ] Yes
[x ] No
```
=> RIA-8363 - Set whether hearing is linked

gradle/wrapper/gradle-wrapper.properties, src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/DecisionAndReasonsStartedFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/ListCaseWithoutHearingRequirementsFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/RecordAdjournmentUpdateRequestHandlerFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/ReviewHearingRequirementsFunctionalTest.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/DecisionAndReasonsStartedHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/ListCaseWithoutHearingRequirementsHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/RecordAdjournmentUpdateRequestHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/ReviewHearingRequirementsHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/HearingService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/DecisionAndReasonsStartedHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/ListCaseWithoutHearingRequirementsHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/RecordAdjournmentDetailsPreparerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/RecordAdjournmentUpdateRequestHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/ReviewHearingRequirementsHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/HearingServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-8014
```
[ ] Yes
[x] No
```
=> RIA-8014 Auto create HMC hearing request when 'Record adjournment details' event is completed

src/contractTest/java/uk/gov/hmcts/reform/iahearingsapi/consumer/refdata/LocationRefDataConsumerTest.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/RecordAdjournmentUpdateRequestHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/clients/refdata/LocationRefDataApi.java
https://tools.hmcts.net/jira/browse/RIA-8491
- Swap service-code parameter name for service_code
- [fix the event error after merging the PR](https://github.com/hmcts/ia-hearings-api/pull/334/commits/95134021dc6ad361f140cc7b5ecee160fe810281) https://github.com/hmcts/ia-hearings-api/pull/331
```
[ ] Yes
[X] No
```
=> RIA-8491 Fix service code parameter name

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadService.java
https://tools.hmcts.net/jira/browse/RIA-8491
return the value of HearingWindowModel in updateHearingWindow method
```
[ ] Yes
[X] No
```
=> RIA-8491 fix the problem of missing return HearingWindowModel object

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CreateHearingPayloadService.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProvider.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CreateHearingPayloadServiceTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProviderTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-8491
- quick fix the duration problem when create hearing service payload
```
[ ] Yes
[X] No
```
=> RIA-8491 quick fix the duration problem

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/hmc/HearingSubChannel.java
https://tools.hmcts.net/jira/browse/RIA-8557
- Added new TEL and VID hearingSubChannel Type for quick fixing the exception
```
[ ] Yes
[X] No
```
=> RIA-8755 auto update is failing for remote hearing

src/main/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/hmc/HmcUpdateDispatcher.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/hmc/HmcUpdateDispatcherTest.java
https://tools.hmcts.net/jira/browse/RIA-8613
RIA-8613 Updates to fix sequencing of handlers execution
```
[ ] Yes
[ ] No
```
=> RIA-8613 Updates to fix sequencing of handlers execution

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/AppellantDetailsMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/InterpreterDetailsMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LegalRepDetailsMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/PartyDetailsMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/SponsorDetailsMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/WitnessDetailsMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CreateHearingPayloadService.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/AppellantDetailsMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/InterpreterDetailsMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LegalRepDetailsMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/PartyDetailsMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/SponsorDetailsMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/WitnessDetailsMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-8608
- fix the bug of not updating the parties hearing channel
- update the unit test
```
[ ] Yes
[X] No
```
=> RIA-8608 hearing channel parties is not updating

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LanguageAndAdjustmentsMapper.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LanguageAndAdjustmentsMapperTest.java
https://tools.hmcts.net/jira/browse/RIA-8635
* Reverts changes made in [RIA-8599](https://tools.hmcts.net/jira/browse/RIA-8599)
```
[ ] Yes
[x] No
```
=> RIA-8635 Revert changes made by RIA-8599

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CreateHearingPayloadService.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProvider.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CreateHearingPayloadServiceTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProviderTest.java
https://tools.hmcts.net/jira/browse/RIA-8654
```
[ ] Yes
[x] No
```
=> RIA-8654 Fix issue with 'autoListFlag' setting

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseFlagsToServiceHearingValuesMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CreateHearingPayloadService.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProvider.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseFlagsToServiceHearingValuesMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CreateHearingPayloadServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-8730
```
[ ] Yes
[x] No
```
=> RIA-8730 Always set 'autoListFlag' to false for appeals hearings

build.gradle, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/HearingExceptionHandlerTest.java
[VUL-5809](https://tools.hmcts.net/jira/browse/VUL-5809)
- Upgraded serenity to 4.1.3
- Upgraded restAssured to 5.4.0
- Removed unused reference to springHystrix
=> RIA-TASK VUL-5809 Upgrade serenity, restAssured, remove springHystrix reference

src/contractTest/java/uk/gov/hmcts/reform/iahearingsapi/consumer/HmcHearingApiConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/iahearingsapi/consumer/HmcHearingApiPostConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/iahearingsapi/consumer/HmcHearingApiPutConsumerTest.java
[RIA-8760](https://tools.hmcts.net/jira/browse/RIA-8760)
- Enabled pact tests
```
[ ] Yes
[x] No
```
=> RIA-8760 Enable pact tests

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CoreCaseDataService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CoreCaseDataServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-8759
```
[ ] Yes
[x] No
```
=> RIA-8759 Bails - refactoring hearings api

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/HearingsToDynamicListMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/utils/HearingsUtils.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/hmc/UnNotifiedHearingsProcessor.java
https://tools.hmcts.net/jira/browse/RIA-8808
RIA-8808 Updates to convert hearings start time from UTC to local date time
```
[ ] Yes
[ ] No
```
=> RIA-8808 Updates to convert hearings start time from UTC to local date time

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/BailCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListedHearingService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/BailListCaseHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/BailListCaseUpdateHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListedHearingServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-8810
* Replace the field with a new Number type field 'listingHearingDuration'
```
[ ] Yes
[x] No
```
=> RIA-8810 Update field 'listingHearingLength'

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-8805
```
[ ] Yes
[x] No
```
=> RIA-8805 Fix issue with field type in 'updateHearingRequest' event

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/hmc/PartyFlagsModel.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/MapperUtils.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/bail/BailCaseFlagsToServiceHearingValuesMapper.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/MapperUtilsTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/bail/BailCaseFlagsToServiceHearingValuesMapperTest.java
https://tools.hmcts.net/jira/browse/RIA-8733
Include case flag date information in Bails manual hearing request payload
```
[ ] Yes
[x ] No
```
=> RIA-8733 - Include case flag date information in Bails manual hearing request payload

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseFlagsToServiceHearingValuesMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/MapperUtils.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/bail/BailCaseFlagsToServiceHearingValuesMapper.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseFlagsToServiceHearingValuesMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/MapperUtilsTest.java
…ng request payload
[RIA-8734
](https://tools.hmcts.net/jira/browse/RIA-8734)
Include case flag date information in Appeals manual hearing request payload
```
[ ] Yes
[ x] No
```
=> RIA-8734 - Include case flag date information in Appeals manual hearing request payload

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/MapperUtils.java
=> RIA-8734 - Fix for datetime parse exception

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/hmc/response/CreateHearingRequest.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/hmc/response/UpdateHearingRequest.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadService.java
[RIA-8832](https://tools.hmcts.net/jira/browse/RIA-8832)
- Optimize equality condition because of fields beings Strings instead of proper YesOrNo classes
```
[ ] Yes
[x] No
```
=> RIA-8832 Fix UpdateHearingRequest payload

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/LocationRefDataService.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/clients/model/refdata/CourtVenue.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/LocationRefDataServiceTest.java
[RIA-8841](https://tools.hmcts.net/jira/browse/RIA-8841)
- Filtered ref data locations by `isHearingLocation` and `courtStatus` attributes
```
[ ] Yes
[x] No
```
=> RIA-8841 Filter locations

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/BailCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/BailListCaseHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/BailListCaseUpdateHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListedHearingService.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProvider.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/BailListCaseHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/BailListCaseUpdateHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListedHearingServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-8795
Set listing location and whether hearing is remote when system triggers Case Listing
```
[ ] Yes
[ x] No
```
=> RIA-8795 - Set listing location and whether hearing is remote when system triggers Case Listing

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/ccd/HoursMinutes.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingRequestHandler.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/ccd/HoursMinutesTest.java
[RIA-8811](https://tools.hmcts.net/jira/browse/RIA-8811)
- populated `changeHearingLength` correctly
```
[ ] Yes
[x] No
```
=> RIA-8811 Change hearing duration value

src/main/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/config/jms/HearingsJmsConfig.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/hmc/listeners/HmcHearingsEventTopicListener.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/hmc/listeners/HmcHearingsEventTopicListenerTest.java
https://tools.hmcts.net/jira/browse/RIA-8812
```
[ ] Yes
[x] No
```
=> RIA-8812 Enable real-time HMC hearing events handling

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/BailListCaseHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/FeatureToggler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/clients/LaunchDarklyFeatureToggler.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/BailListCaseHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/clients/LaunchDarklyFeatureTogglerTest.java
https://tools.hmcts.net/jira/browse/RIA-8795
Allow service user to get feature flag value when handling JMS
```
[ ] Yes
[ x] No
```
=> RIA-8795 - Allow service user to get feature flag value when handling JMS

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingRequestHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/BailListCaseHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/BailListCaseUpdateHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListedHearingService.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/LocationRefDataService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingsRequestHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/BailListCaseHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/BailListCaseUpdateHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListedHearingServiceTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/LocationRefDataServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-8942
Fix Listing location not being displayed in overview page
```
[ ] Yes
[x ] No
```
=> RIA-8942 - Fix Listing location not being displayed

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/BailListCaseHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListCaseHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListedHearingService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListCaseHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListedHearingServiceTest.java
…stem triggers List the case event
- [ x] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/RIA-8796
Set listing location and whether hearing is remote when system triggers "List the case"
Also rollback previous changes to keep the existing implementation when refdata is enabled
```
[ ] Yes
[ x] No
```
=> RIA-8796 - Set listing location and whether hearing is remote when system triggers "List the case"

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapper.java
https://tools.hmcts.net/jira/browse/RIA-8987
```
[ ] Yes
[x] No
```
=> RIA-8987 Ensure parties' hearing channels are populated during hearing update

src/functionalTest/resources/templates/minimal-appeal-started.json, src/functionalTest/resources/templates/minimal-appeal-submitted.json, src/functionalTest/resources/templates/start-appeal-aip.json, src/functionalTest/resources/templates/start-appeal-legalrep.json, src/functionalTest/resources/templates/start-appeal.json, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListedHearingService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListedHearingServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-8943
```
[ ] Yes
[x] No
```
=> RIA-8943 Fix issue in the logic to compare 'PartiesNotifiedResponses'

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditListCaseHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListedHearingService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditListCaseHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListedHearingServiceTest.java
…stem triggers Edit case listing
https://tools.hmcts.net/jira/browse/RIA-8797
```
[ ] Yes
[x] No
```
=> RIA-8797 - Set listing location and whether hearing is remote when system triggers "Edit case listing"

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditListCaseHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListCaseHandler.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditListCaseHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListCaseHandlerTest.java
Refactored to use ccd field to determine appeals refdata enabled
```
[ ] Yes
[x ] No
```
=> RIA-8797 - Refactored to use ccd field to determine appeals refdata enabled

src/main/resources/config.properties
RIA-0000 trigger master build
RIA-0000 trigger master build
```
[ ] Yes
[ ] No
```
=> RIA-0000 trigger master build

src/contractTest/java/uk/gov/hmcts/reform/iahearingsapi/consumer/hmc/HmcHearingApiGetConsumerTest.java
Fix pact failure
```
[ ] Yes
[x ] No
```
=> RIA-TASK - Fix pact failure

src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/DecideAnApplicationHandlerFunctionalTest.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/hmc/listeners/HmcHearingsEventTopicListener.java
Enable back real time message processing
=> RIA-8954 - enable real time message processing

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/RecordAdjournmentUpdateRequestHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingRequestSubmit.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateInterpreterDetailsHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/RecordAdjournmentUpdateRequestHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingsRequestSubmitTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateInterpreterDetailsHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-9115
Fix for latest case details not being assigned to update hearing payload
```
[ ] Yes
[ x] No
```
=> RIA-9115 - Fix for latest case details not being assigned to update hearing payload

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/hmc/ContactPreference.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/AppellantDetailsMapper.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/AppellantDetailsMapperTest.java
… preference to hearing payload
https://tools.hmcts.net/jira/browse/RIA-9127
For appellant pass either mobile or email based on contact preference to hearing payload
```
[ ] Yes
[ x] No
```
=> RIA-9127 - For appellant pass either mobile or email based on contact preference to hearing payload

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingRequestSubmit.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/SendServiceDataToHmcHandler.java
https://tools.hmcts.net/jira/browse/RIA-9146
add logs for investigation
```
[ ] Yes
[x] No
```
=> RIA-9146 - add logs for investigation

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/SendServiceDataToHmcHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/hmc/listeners/HmcHearingsEventTopicListener.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/TestUtils.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/SendServiceDataToHmcHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/hmc/listeners/HmcHearingsEventTopicListenerTest.java
https://tools.hmcts.net/jira/browse/RIA-9146
Fix HMC response not found error
```
[ ] Yes
[x ] No
```
=> RIA-9146 - Fix HMC response not found error

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadServiceTest.java
…the field was cleared
```
[ ] Yes
[ x] No
```
=> RIA-TASK - Fix for when hearing is updated hearing linked flag returns false as the field was cleared

src/functionalTest/resources/templates/start-appeal-aip.json, src/functionalTest/resources/templates/start-appeal-legalrep.json, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadServiceTest.java
- [ x] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/RIA-9195
```
[ ] Yes
[ ] No
```
=> RIA-9195 - fix for hmctsInternalCaseName not updating in the Auto update hearing request

src/functionalTest/resources/templates/start-appeal-aip.json, src/functionalTest/resources/templates/start-appeal-legalrep.json
=> RIA-TASK - fix functional test

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/NextHearingDetails.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/ListEditCaseHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/NextHearingDateService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/ListEditCaseHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListedHearingServiceTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/NextHearingDateServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-8921
```
[ ] Yes
[x] No
```
=> RIA-8921 Set next hearing date when hearing is listed/edited

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListCmrHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/NextHearingDateService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListCmrHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/NextHearingDateServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-8945
https://tools.hmcts.net/jira/browse/RIA-8946
```
[ ] Yes
[x] No
```
=> RIA-8945 Set next hearing date when CMR hearing is listed/updated

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-8921
```
[ ] Yes
[x] No
```
=> RIA-8921 Update case/admin officer roles' access to events

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-8921
```
[ ] Yes
[x] No
```
=> RIA-8921 Update system user role's access to events

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/NextHearingDateService.java
=> RIA-8921 Prevent possible NullPointerException

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/RecordAdjournmentUpdateRequestHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingRequestSubmit.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/HearingService.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/clients/HmcHearingApi.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/RecordAdjournmentUpdateRequestHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingsRequestSubmitTest.java
Reverts hmcts/ia-hearings-api#447
=> Revert "RIA-8936 Simulate HMC failure for 'updateHearingRequest' and 'record…"

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditListCaseHandler.java
RIA-9246 Updates to handle hearing channel for non-integrated cases
RIA-9246 Updates to handle hearing channel for non-integrated cases
```
[ ] Yes
[ ] No
```
=> RIA-9246 Updates to handle hearing channel for non-integrated cases

build.gradle, src/contractTest/java/uk/gov/hmcts/reform/iahearingsapi/consumer/hmc/HmcHearingApiConsumerTestBase.java, src/contractTest/java/uk/gov/hmcts/reform/iahearingsapi/consumer/hmc/HmcHearingApiDeleteConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/iahearingsapi/consumer/hmc/HmcHearingApiGetConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/iahearingsapi/consumer/hmc/HmcHearingApiPostConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/iahearingsapi/consumer/hmc/HmcHearingApiUpdateConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/iahearingsapi/consumer/hmc/HmcPartiesNotifiedApiUpdateConsumerTest.java, src/contractTest/java/uk/gov/hmcts/reform/iahearingsapi/consumer/hmc/IacHearingApiGetConsumerTest.java
https://tools.hmcts.net/jira/browse/RIA-9246
```
[ ] Yes
[x] No
```
=> RIA-9246 Get participantVersion from GIT_COMMIT env var

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditListCaseHandler.java
RIA-9246 Edit listing fix for non integrated cases
RIA-9246 Edit listing fix for non integrated cases
```
[ ] Yes
[ ] No
```
=> RIA-9246 Edit listing fix for non integrated cases

src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/HearingsControllerFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/UpdateHearingRequestFunctionalTest.java
RIA-0000 Update to disable FT on  UpdateHearingRequestFunctionalTest.java
RIA-0000 Update to disable FT on  UpdateHearingRequestFunctionalTest.java
```
[ ] Yes
[ ] No
```
=> RIA-0000 Update to disable FT on  UpdateHearingRequestFunctionalTest.java

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/CancelledHearingHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CoreCaseDataService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/CancelledHearingHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CoreCaseDataServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-8923
```
[ ] Yes
[x] No
```
=> RIA-8923 Next hearing date is set when substantive hearing is cancelled

Jenkinsfile_CNP, charts/ia-hearings-api/Chart.yaml, charts/ia-hearings-api/values.yaml, src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/HearingsControllerFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/UpdateHearingRequestFunctionalTest.java
- [ x] tests have been updated / new tests has been added (if needed)
Update to point functional tests to AAT
```
[ ] Yes
[x ] No
```
=> RIA-9256  Update to point functional tests to AAT

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/CmrHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListedHearingService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/CmrHandlerTest.java
https://tools.hmcts.net/jira/browse/RIA-8919
```
[ ] Yes
[x] No
```
=> RIA-8959 Set next hearing date when CMR hearing is cancelled

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/CancelledHearingHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CoreCaseDataService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/CancelledHearingHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CoreCaseDataServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-8947
Clear hearing details on case when integrated substantive hearing is cancelled 
```
[ ] Yes
[ ] No
```
=> RIA-8947 Clear hearing details on case 

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/ccd/Event.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/NextHearingDateHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/CancelledHearingHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/CmrHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CoreCaseDataService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/ccd/EventTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/NextHearingDateHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/CancelledHearingHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CoreCaseDataServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-9262
```
[ ] Yes
[x] No
```
=> RIA-9262 Update eventid of 'Set next hearing date'

build.gradle, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditListCaseHandler.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditListCaseHandlerTest.java
https://tools.hmcts.net/jira/browse/RIA-9259
```
[ ] Yes
[x] No
```
=> RIA-9259 Refactor the code for handling listed hearings

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/NextHearingInfoHandler.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/NextHearingInfoHandlerTest.java
https://tools.hmcts.net/jira/browse/RIA-9038
Added CMR_LISTING, CMR_RE_LISTING to NextHearingInfoHandler to resolve issue when CMR - Reconfigure work allocation tasks when next hearing date is updated
=> RIA-9038 Cmr fix

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/SubstantiveHearingCancelledHandler.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/SubstantiveHearingCancelledHandlerTest.java
https://tools.hmcts.net/jira/browse/RIA-9485
```
[ ] Yes
[x] No
```
=> RIA-9485 Refactor handler for substantive hearing cancellation

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/SubstantiveHearingEditedHandler.java
https://tools.hmcts.net/jira/browse/RIA-9476
```
[ ] Yes
[x] No
```
=> RIA-9476 Handle missing 'list case hearing date'

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/NextHearingInfoHandler.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/NextHearingInfoHandlerTest.java
https://tools.hmcts.net/jira/browse/RIA-9485
```
[ ] Yes
[x] No
```
=> RIA-9485 Calculate next hearing date on hearing cancelled event

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/RIA-9485
```
[ ] Yes
[x] No
```
=> RIA-9485 Give admin and system roles access to 'hearingCancelled' event

src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/AutoRequestHearingFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/CcdCaseCreationTest.java, src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/DecideAnApplicationHandlerFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/RecordAdjournmentDetailsPreparerFunctionalTest.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProvider.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/clients/HearingRequestGenerator.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProviderTest.java
https://tools.hmcts.net/jira/browse/RIA-9261
```
[ ] Yes
[x] No
```
=> RIA-9261 Enable functional tests

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LegalRepDetailsMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LegalRepOrgDetailsMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/MapperUtils.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/PartyDetailsMapper.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LegalRepDetailsMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LegalRepOrgDetailsMapperTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/MapperUtilsTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/PartyDetailsMapperTest.java
https://tools.hmcts.net/jira/browse/RIA-9586
Added legal rep handling for ICC
```
[ ] Yes
[ x ] No
```
=> RIA-9586 Added legal rep handling for ICC

Jenkinsfile_nightly
https://tools.hmcts.net/jira/browse/DIAC-690
```
[ ] Yes
[ ] No
```
=> DIAC-690 - add nightly secrets for functional tests

Jenkinsfile_nightly
=> DIAC-690 - fix nightly

Jenkinsfile_nightly
=> DIAC-690 - assign env var in jenkins nightly

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/BailCaseFieldDefinition.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/BailListCaseHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/BailListCaseUpdateHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/CancelledHearingHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditListCaseHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListCmrHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListedHearingService.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/HearingService.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/hmc/HmcMessageProcessor.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/BailListCaseHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/CancelledHearingHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListCaseHandlerTest.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/ListedHearingServiceTest.java
=> DIAC-652 Diac 863 diac 652 adding hearing

build.gradle, charts/ia-hearings-api/Chart.yaml, config/owasp/suppressions.xml
=> DIAC-000 - update dependencycheck from 10.0.3 to 12.1.0

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditListCaseHandler.java
=> DIAC-656 Added DECISION state to EditListCaseHandler

src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/AutoRequestHearingFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/CcdCaseCreationTest.java, src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/DecideAnApplicationHandlerFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/EndAppealRequestSubmitHandlerFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/HearingsControllerFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/RecordAdjournmentDetailsPreparerFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/UpdateHearingRequestFunctionalTest.java
=> Diac 864 hmc int test fix

.github/workflows/ci.yml, charts/ia-hearings-api/values.preview.template.yaml, src/main/resources/application.yaml
=> SNI-7502 - deployment id only for preview not other environments

config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadService.java
=> SNI-7482 - update CaseDeepLink for LA on updating hearing request

.github/workflows/pr-title-validation.yml, charts/ia-hearings-api/Chart.yaml, charts/ia-hearings-api/values.yaml, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/hmc/listeners/HmcHearingsEventTopicListener.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/hmc/listeners/HmcHearingsEventTopicListenerTest.java
https://tools.hmcts.net/jira/browse/DIAC-1145
```
[ ] Yes
[x] No
```
=> DIAC-1145 Fix HMC message format exception

src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/CreateHearingPayloadService.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadService.java, src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadServiceTest.java
https://tools.hmcts.net/jira/browse/SNI-7482
Fix CaseDeepLink on update hearing request
```
[x] Yes
[ ] No
```
=> SNI-7482 Fix CaseDeepLink on update hearing request

build.gradle, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/ccd/HoursMinutes.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingRequestHandler.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingRequestSubmit.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/HandlerUtils.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LanguageAndAdjustmentsMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/bail/BailCaseDataToServiceHearingValuesMapper.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/LocationRefDataService.java, src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadService.java
=> DIAC-1451 CVE fix

config/owasp/suppressions.xml
=> DIAC-855 suppressions
