- .git-config/hooks/commit-msg
- .git-config/hooks/pre-commit
- .github/workflows/pr-title-validation.yml
- README.md
RIA-7384
Add git hooks to help enforcing conventions.
Developers will need to opt-in to this, so it's not going to be disruptive.
```
[ ] Yes
[x] No
```
> RIA-7384 Enforce conventions on commit messages and branches

- Jenkinsfile_CNP
- Jenkinsfile_nightly
- Jenkinsfile_parameterized
- charts/ia-hearings-api/Chart.yaml
- charts/ia-hearings-api/values.yaml
- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/ConfigValidatorAppListener.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/ConfigValidatorAppListenerTest.java
https://tools.hmcts.net/jira/browse/RIA-7383
Adding ia.config.validator.secret to application.yaml + ConfigValidatorAppListener to check to see if secrets are being applied by azure.
```
[ ] Yes
[x] No
```
> RIA-7378 - preventing application startup if secrets can't be found

- .github/renovate.json
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/AppellantDetailsMapper.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LanguageAndAdjustmentsMapper.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/WitnessDetailsMapper.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProvider.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/AppellantDetailsMapperTest.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LanguageAndAdjustmentsMapperTest.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/WitnessDetailsMapperTest.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProviderTest.java
[RIA-7617](https://tools.hmcts.net/jira/browse/RIA-7617)
- Fix the logic in order to populate `reasonableAdjustments`, `otherReasonableAdjustmentDetails` and `interpreterLanguage` inside the partyDetails of appellant and witnesses
What this code is supposed to do is:
- go through the each group of flags per party (appellant flags, witness 1 flags, witness 2 flags etc.) and for each:
- separate the language flags from reasonable adjustments flags
- write the flag-codes of the reasonable adjustment flags in partyDetails.individualDetails.reasonableAdjustments
- sort the language flags so that one with language-code is selected and its code populates partyDetails.individualDetails.interpreterLanguage
- take the remaining language flags (with and without language-code) and write its full name …
> RIA-7617 Fix language and adjustment fields inside partyDetails

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/hmc/ListAssistCaseStatus.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/SendServiceDataToHmcHandler.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/HearingService.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/SendServiceDataToHmcHandlerTest.java
[RIA-8020](https://tools.hmcts.net/jira/browse/RIA-8020)
- Added missing constants in `ListAssistCaseStatus`
- Prevented update of partiesNotified when either versionNumber or receivedDateTime is null, as they're both needed to retrieve an entry where partiesNotified are stored (the HearingResponse table)
```
[ ] Yes
[x] No
```
> RIA-8020 Prevent partiesNotifiedUpdate when needed info missing

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/InterpreterBookingStatus.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/AppellantDetailsMapper.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/PartyDetailsMapper.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/WitnessDetailsMapper.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/utils/InterpreterLanguagesUtils.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/AppellantDetailsMapperTest.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/WitnessDetailsMapperTest.java
[RIA-7700](https://tools.hmcts.net/jira/browse/RIA-7700)
- Added booking status of interpreters to `otherReasonableAdjustmentsDetails` of individual details for each party (witnesses and appellant)
```
[ ] Yes
[x] No
```
> RIA-7700 Booking statuses in otherReasonableAdjustmentsDetails

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/AppellantDetailsMapper.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/PartyDetailsMapper.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/WitnessDetailsMapper.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/AppellantDetailsMapperTest.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/PartyDetailsMapperTest.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadServiceTest.java
[RIA-7972](https://tools.hmcts.net/jira/browse/RIA-7972)
- made any update of the hearing request rebuild the party details, so that each has the updated content for `otherReasonableAdjustmentDetails` where the interpreter booking statuses are supposed to be written
- changed the logic surrounding the qualifying booking statuses, so that `notRequested` is considered when the party has both spoken and sign languages (so that _spoken=notRequested_ and _sign=requested_ the otherReasonableAdjustmentDetails property contains `Status (Spoken): Not Requested; Status (Sign): Requested` instead of `Status: Requested`
```
[ ] Yes
[x] No
```
> RIA-7972 Write party details when updating hearing requests

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/WitnessDetailsMapper.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/WitnessDetailsMapperTest.java
[RIA-7700](https://tools.hmcts.net/jira/browse/RIA-7700)
- Infer index from position in collection rather than IdValue's ids (string numbers in some cases, uuids in AIP before updating hearing requirements)
```
[ ] Yes
[x] No
```
> RIA-7700 Infer index of witness elements

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/hmc/listeners/HmcHearingsEventTopicListener.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/hmc/listeners/HmcHearingsEventTopicListenerTest.java
[https://tools.hmcts.net/jira/browse/RIA-8082](https://tools.hmcts.net/jira/browse/RIA-8082)
- Commented out condition that used to exclude non-EXCEPTION messages for live processing (all messages being live processed again)
(temporary solution to unblock testing until batch processing works again)
```
[ ] Yes
[x] No
```
> RIA-8082 Enable processing of all messages temporarily

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateInterpreterDetailsHandler.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditListCaseHandler.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/HandlerUtils.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/HearingService.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/exception/HmcException.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/HearingExceptionHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/HearingServiceTest.java
[RIA-8155](https://tools.hmcts.net/jira/browse/RIA-8155)
- Changed HmcException to retail the original message of the exception it wraps
- Extra logging for user details and the Feign exception thrown when updating hearing request
```
[ ] Yes
[x] No
```
> RIA-8155 Added extra logging and changed HmcException

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/hmc/listeners/HmcHearingsEventTopicListener.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/hmc/listeners/HmcHearingsEventTopicListenerTest.java
[https://tools.hmcts.net/jira/browse/RIA-8082](https://tools.hmcts.net/jira/browse/RIA-8082)
- Reverted the changes that disabled batch-processing, which can be re-enabled now
```
[ ] Yes
[x] No
```
> RIA-8082 Disable live processing of messages

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProvider.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProviderTest.java
https://tools.hmcts.net/jira/browse/RIA-8093
For S5 numberOfPhysicalAttendees population logic takes Home Office in to account
```
[ ] Yes
[ x] No
```
> RIA-8093 - Added respondent into the count of attendees

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/BailCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/bail/ApplicantDetailsMapper.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/bail/FinancialConditionSupporterDetailsMapper.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/utils/InterpreterLanguagesUtils.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/bail/ApplicantDetailsMapperTest.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/bail/FinancialConditionSupporterDetailsMapperTest.java
https://tools.hmcts.net/jira/browse/RIA-8006
- Added booking status of interpreters (spoken and sign) to otherReasonableAdjustmentsDetails of individual details for each party (FCS and applicant)
```
[ ] Yes
[X] No
```
> RIA-8006 Interpreter booking statuses added to other reasonable adjs

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/BailCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/bail/BailCaseDataToServiceHearingValuesMapper.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProvider.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/bail/BailCaseDataToServiceHearingValuesMapperTest.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProviderTest.java
[RIA-8092](https://tools.hmcts.net/jira/browse/RIA-8092)
- Scenario 8 required HearingWindow to have a startDate 28 working days in the future when the bail case state is `decisionConditionalBail`, instead of the standard 2 working days for startDate and 7 working days for endDate
```
[ ] Yes
[x] No
```
> RIA-8092 Make hearingWindow have a start date 28 working days later

- build.gradle
- src/functionalTest/java/uk/gov/hmcts/reform/iahearingsapi/DecideAnApplicationHandlerFunctionalTest.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/ccd/Event.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/DecideAnApplicationHandler.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/ccd/EventTest.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/DecideAnApplicationHandlerTest.java
[RIA-7780](https://tools.hmcts.net/jira/browse/RIA-7780)
- Added handling of `decideAnApplication` to cancel all hearings that are in `HEARING_REQUESTED`, `AWAITING_LISTING`, `UPDATE_REQUESTED`, `UPDATE_SUBMITTED`, `LISTED` HmcStatus and are `Substantive`
- The delegation of this event to IA-HEARINGS-API only happens according to conditions set out in IA-CASE-API (the application is of type` Change hearing type`, is `Granted` and the state of the case is between `listing` and `decision`)
> RIA-7780 Handle DecideAnApplication event

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/DecideAnApplicationHandler.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/DecideAnApplicationHandlerTest.java
[RIA-8397](https://tools.hmcts.net/jira/browse/RIA-8397)
- Made the handler set `manualCanHearingRequired` to NO when deletion is successful
```
[ ] Yes
[x] No
```
> RIA-8397 Made manualCanHearingRequired set to NO when deletion successful

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapper.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapperTest.java
[RIA-8407](https://tools.hmcts.net/jira/browse/RIA-8407)
- Instead of throwing an exception when `localAuthorityPolicy` is missing, it'll just default to null string
```
[ ] Yes
[x] No
```
> RIA-8407 Default to empty string if localAuthorityPolicy null

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/ChangeOrganisationRequest.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/CaseDataToServiceHearingValuesMapper.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LegalRepOrgDetailsMapper.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/MapperUtils.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/PartyDetailsMapper.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LegalRepOrgDetailsMapperTest.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/MapperUtilsTest.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/PartyDetailsMapperTest.java
[RIA-8432](https://tools.hmcts.net/jira/browse/RIA-8432)
[RIA-8433](https://tools.hmcts.net/jira/browse/RIA-8433)
- Made `LegalRepOrgDetailsMapper` use `legalRepCompany` instead of `legalRepCompanyName`
- Made `PartyDetailsMapper`  generate LegalRepDetails and LegalRepOrgDetails (`party` entries in the hearing payload) when the journey isn't `AIP` && `changeOrganisationRequestField` isn't present (so representation isn't undergoing change)
> RIA-8432 RIA-8433 tweak legal rep party

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/DecisionWithoutHearingListed.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/DecisionWithoutHearingListedTest.java
[RIA-8419](https://tools.hmcts.net/jira/browse/RIA-8419)
- Invert the condition to trigger `DecisionWithoutHearingListed` so it's triggered when partiesNotified returns empty (meaning this is the first LISTED update received, otherwise this would be a following update, which should be ignored)
```
[ ] Yes
[x] No
```
> RIA-8419 Trigger DecisionWithoutHearingListed if no partiesNotified present

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/hmc/HmcUpdateDispatcher.java
https://tools.hmcts.net/jira/browse/RIA-8552
Fix to prevent handlers being triggered from the outcome of another handler
```
[ ] Yes
[ x] No
```
> RIA-8552 -  Fix to prevent handlers being triggered from the outcome of another handler

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditListCaseHandler.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditListCaseHandlerTest.java
[RIA-8593](https://tools.hmcts.net/jira/browse/RIA-8593)
- Set listing time (9:45 or 10:00) while triggering `editListCase` based on real location as per List Assist update instead of the location shown on the UI (which becomes Remote Hearing when hearing channel is VID or TEL and skews the time towards 10:00 when it's remote and in Glasgow, since venue Remote Hearing ≠ venue Glasgow)
```
[ ] Yes
[x] No
```
> RIA-8593 Set time 9:45 / 10:00 based on real LA hearing venue even if remote

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LanguageAndAdjustmentsMapper.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/LanguageAndAdjustmentsMapperTest.java
[RIA-8599](https://tools.hmcts.net/jira/browse/RIA-8599)
- `PF0015` flag to be included in Reasonable Adjustments field of partyDetails for Bails along SM and RA flags
```
[ ] Yes
[x] No
```
> RIA-8599 PF0015 in list of flags for Reasonable Adjustments in party details (Bails)

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/hmc/HearingSubChannel.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingRequestHandler.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingsRequestHandlerTest.java
[RIA-8601](https://tools.hmcts.net/jira/browse/RIA-8601)
- Add more values to `HearingSubChannel`
- Use `changeHearingVenue` instead of `changeHearingLocation` because it's of type "hearingVenue" and renders correctly on XUI
> RIA-8601 Add all hearingSubChannel types to enum

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/AutoRequestHearingHandler.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/AutoRequestHearingHandlerTest.java
https://tools.hmcts.net/jira/browse/RIA-8449
* This PR fixes a bug resulting from the refactoring done in RIA-8449.
* The bug causes an exception to be thrown while handling events that do not auto create hearing. 
```
[ ] Yes
[x] No
```
> RIA-8449 Fix bug in AutorequestHandler's canHandle method

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadService.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadServiceTest.java
https://tools.hmcts.net/jira/browse/RIA-8612
- rename from nextHearingLocation to the nextHearingVenue
- retrieve the value from reference data for nextHearingVenue instead of using fixedList
- update unit test
```
[ ] Yes
[X] No
```
> RIA-8612 change hearing location to ref data in record adjournment details event

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditListCaseHandler.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/servicedatahandlers/EditListCaseHandlerTest.java
[RIA-8619](https://tools.hmcts.net/jira/browse/RIA-8619)
- Made editCaseListing trigger if there's a change in the date and time of the hearing (the time being calculated based on whether the hearing is physically in Glasgow or elsewhere)
- Reverted the hearingCentre check between old and new value back to what it was (which compares the two location values instead of location value VS. physical venue): so `remoteHearing` == `remoteHearing`
```
[ ] Yes
[x] No
```
> RIA-8619 Change logic around the triggers for editCaseListing

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingRequestHandler.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingsRequestHandlerTest.java
[RIA-8608](https://tools.hmcts.net/jira/browse/RIA-8608)
- After listing, when triggering `updateHearingRequest`, the hearing channel radio-button list would only display 1 option (the previously selected hearing channel), while it should display all options with the previously selected option prepopulated.
```
[ ] Yes
[x] No
```
> RIA-8608 Populate LoV of hearing channel dynamic list

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingRequestHandler.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingsRequestHandlerTest.java
[RIA-8601](https://tools.hmcts.net/jira/browse/RIA-8601)
- `hearingLocation` list was not getting populated when `listCaseHearingCentre` has an empty epimmsId (remoteHearing or decisionWithoutHearing), now it does (with no preselection)
```
[ ] Yes
[x] No
```
> RIA-8601 Populate LoV of locations when listCaseHearingCentre is remote

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/hmc/ServiceHearingValuesModel.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/utils/PayloadUtils.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/utils/PayloadUtilsTest.java
[RIA-8671](https://tools.hmcts.net/jira/browse/RIA-8671url)
- Made number of physical attendees be null instead of 0 if there are no channels attributed to parties' individual details
```
[ ] Yes
[x] No
```
> RIA-8671 Make physical attendees null when no hearing channel

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingRequestHandler.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/infrastructure/PreSubmitCallbackDispatcher.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingsRequestHandlerTest.java
[RIA-8659](https://tools.hmcts.net/jira/browse/RIA-8659)
- Restricted current logic that is in place for what was the only midEvent trigger for `updateHearingRequest` to the page for which it is intended
```
[ ] Yes
[x] No
```
> RIA-8659 Read pageId for existing midEvent logic

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingRequestHandler.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingRequestSubmit.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingsRequestSubmitTest.java
[RIA-8634](https://tools.hmcts.net/jira/browse/RIA-8634)
- Made actually requested values be overwritten by newly requested values in `updateHearingRequest`:
- `requestHearingChannel` → `changeHearingType` + `hearingChannel`
- `hearingLocation` → `changeHearingVenue`
- `requestHearingLength` → `changeHearingDuration` + `listCaseHearingLength`
- `requestHearingDate` → `changeHearingDate`
```
[ ] Yes
[x] No
```
> RIA-8632 Overwrite newly selected values onto originally requested values

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateInterpreterDetailsHandler.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateInterpreterDetailsHandlerTest.java
[RIA-8669](https://tools.hmcts.net/jira/browse/RIA-8669)
- No exception thrown when executing `updateInterpreterBookingStatus` and `updateInterpreterDetails` if no substantive hearing isn't found, as they can be triggered before a hearing's been requested and they should complete successfully
```
[ ] Yes
[x] No
```
> RIA-8669 Make hearing update not fail if no hearings present if not yet requested

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingRequestSubmit.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingsRequestSubmitTest.java
[RIA-8659](https://tools.hmcts.net/jira/browse/RIA-8659)
- Remove exception being thrown when date range to be persisted misses start or end date (validation on missing both dates exists in the previous page)
```
[ ] Yes
[x] No
```
> RIA-8659 Remove thrown exceptions if start or end date in date range missing

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/HearingsToDynamicListMapper.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/RecordAdjournmentDetailsPreparerTest.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingRequestPreparerTest.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/mappers/HearingsToDynamicListMapperTest.java
[RIA-8741](https://tools.hmcts.net/jira/browse/RIA-8741)
- Removed UPDATE_REQUESTED from the hmcStatuses of hearings that should populate the dropdown list of updatable hearings in `recordAdjournmentDetails` and `updateHearingRequest` (UPDATE_REQUESTED and HEARING_REQUESTED are statuses of hearings that have persisted in HMC but not yet List Assist: they become UPDATE_SUBMITTED or AWAITING_LISTING when LA acknowledges the update/creation f the hearing request)
```
[ ] Yes
[x] No
```
> RIA-8741 Remove UPDATE_REQUESTED from hmcStatuses of hearings that qualify for an update

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/AsylumCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingRequestHandler.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingRequestSubmit.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadService.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingsRequestHandlerTest.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingsRequestSubmitTest.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadServiceTest.java
[RIA-8757](https://tools.hmcts.net/jira/browse/RIA-8757)
- Swapped `requestHearingDate` for `requestHearingDate1`, which uses Date instead of DateTime
- Update only selected fields during 'updateHearingRequest' event ([RIA-8805](https://tools.hmcts.net/jira/browse/RIA-8805))
```
[ ] Yes
[x] No
```
> RIA-8757 Use requestHearingDate1 (Date) instead of requestHearingDate

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingRequestSubmit.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/utils/HearingsUtils.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/handlers/presubmit/UpdateHearingsRequestSubmitTest.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/utils/HearingsUtilsTest.java
[RIA-8757](https://tools.hmcts.net/jira/browse/RIA-8757)
- Fix date time compatibility problem between dates / dateTimes for `requestHearingDate1` field
```
[ ] Yes
[x] No
```
> RIA-8757 fix firstDateTimeMustBe

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/entities/BailCaseFieldDefinition.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProvider.java
- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/utils/HearingsUtils.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/ServiceHearingValuesProviderTest.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/utils/HearingsUtilsTest.java
[RIA-8821](https://tools.hmcts.net/jira/browse/RIA-8821)
- Use `hearingCentreRefData` to populate caseManagementLocationCode in the hearing request payload when the LaunchDarkly location ref data feature is enabled
```
[ ] Yes
[x] No
```
> RIA-8821 Use hearingCentreRefData to populate caseManagementLocationCode in payload

- src/main/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadService.java
- src/test/java/uk/gov/hmcts/reform/iahearingsapi/domain/service/UpdateHearingPayloadServiceTest.java
- [z ] commit messages are meaningful and follow good commit message guidelines
- [z ] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/RIA-9146
Fix for HMC failed validation when (non null) empty hearing window object is passed in payload
```
[ ] Yes
[ ] No
```
> RIA-9146 - Fix for HMC failed validation when (non null) empty hearing window object is passed in payload

- build.gradle
- config/owasp/suppressions.xml
[DIAC-590](https://tools.hmcts.net/jira/browse/DIAC-590)
add dependency set to org.springframework.security:spring-security-rsa:1.1.1 fixing [CVE-2023-33202](https://github.com/advisories/GHSA-wjxj-5m7g-mg7q)
add dependency set to org.springframework.security:spring-security-oauth2-client:5.8.11 fixing [CVE-2023-1370](https://github.com/advisories/GHSA-493p-pfq6-5258)
```
[ ] Yes
[ ] No
```
> DIAC-590 update spring-security packages
